<div class="h-screen p-10">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <script src="https://unpkg.com/alpinejs@2.x.x/dist/alpine.min.js" defer></script>
    <div class="border border-pink-700 h-full flex flex-col justify-between relative m-auto w-1/2 m-auto">
        <div class="text-center">
            @if (session()->get('image_url'))
            <div class="mt-6">
                <img src="{{ session()->get('image_url') }}" alt="Uploaded Image"
                    class="w-2/6 h-auto mx-auto rounded-lg shadow-lg">
            </div>
            @endif
            @if (session()->get('text'))
            <h1 class="text-center italic font-bold m-4">Text generated from an image</h1>
            <div class="text-justify px-6 mt-2">
                <p class="py-4">{{ session()->get('text') }}</p>
                <h2 class="italic font-bold">Sentiment analysis of text generated by an image</h2>
                <p class="py-2">
                    <b>{{ session()->get('sentiments')['result'][0]['label'] }}</b> -
                    {{ session()->get('sentiments')['result'][0]['score'] }}
                </p>
                <p class="py-2">
                    <b>{{ session()->get('sentiments')['result'][1]['label'] }}</b> -
                    {{ session()->get('sentiments')['result'][1]['score'] }}
                </p>
            </div>
            @endif
        </div>
        <div class="absolute bottom-0 w-full p-6 bg-gray-50 border-t border-gray-200">
            <form class="space-y-3 text-center" method="post" enctype="multipart/form-data"
                wire:submit.prevent="uploadImage">
                <div x-data="{ selectedFile: '' }">
                    <div
                        class="relative w-full h-10 border border-gray-300 rounded-lg overflow-hidden pl-3 pr-1 flex items-center">
                        <input type="file" name="file" id="file-upload" wire:model="file"
                            class="w-1/2 h-full opacity-0 cursor-pointer absolute top-0 left-0 right-0" accept="image/*"
                            @change="selectedFile = $event.target.files[0]? $event.target.files[0].name : ''; $wire.deleteExistingImage()">
                        <label for="file-upload"
                            class="text-gray-500 font-medium truncate w-full h-full flex items-center">
                            <span x-text="selectedFile || 'No file selected'"></span>
                        </label>
                        <button type="submit"
                            class="bg-blue-500 text-white font-bold rounded-lg px-3 py-1 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-400">
                            Upload
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    window.onload = function() {
            @php
            if (session()->get('image_url')) {
                $imagePath = storage_path('app/public/' . basename(session()->get('image_url')));
                if (file_exists($imagePath)) {
                    unlink($imagePath);
                }
                session()->forget('image_url');
            }
            @endphp
        };
</script>
